spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gcp
    username: ktk
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
