spring:
  datasource:
    url: jdbc:mysql://mysql:3307/test
    username: root
    password: 1234
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
  jpa:
    hibernate:
      ddl-auto: create
