name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Permission
      run: chmod 744 gradlew

    - name: build
      run: ./gradlew clean build
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build .
